### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test1234@email.com",
    "password": "123test1234"
}

### Signin User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test1234@email.com",
    "password": "123test1234"
}

### Find user with ID
GET http://localhost:3000/auth/2

### Find all users with email
GET http://localhost:3000/auth?email=test@email.com

### Delete user with ID
DELETE http://localhost:3000/auth/1445

### Update user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "abc@test.com"
}

### Get the currently signed user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout